- id: careqa_en
  module: careqa
  num_examples: -1
  verbose: false
  env_args:
    split: en

- id: careqa_en
  module: careqa
  num_examples: -1
  verbose: false
  env_args:
    shuffle_answers: true
    split: en
  matrix:
    shuffle_seed: [1618, 9331]
  matrix_id_format: "{base}-rollout{shuffle_seed}"