- id: m_arc
  module: m_arc
  num_examples: -1
  verbose: false

- id: m_arc
  module: m_arc
  num_examples: -1
  verbose: false
  env_args:
    shuffle_answers: true
  matrix:
    shuffle_seed: [1618, 9331]
  matrix_id_format: "{base}-rollout{shuffle_seed}"
