- id: med_mcqa
  module: med_mcqa
  rollouts_per_example: 1
  num_examples: -1
  verbose: false

- id: med_mcqa
  module: med_mcqa
  rollouts_per_example: 1
  num_examples: -1
  verbose: false
  env_args:
    shuffle_answers: true
  matrix:
    shuffle_seed: [1618, 9331]
  matrix_id_format: "{base}-rollout{shuffle_seed}"
